### ISSUE TITLE
run django server doesn't work

### ISSUE THREAD

**Issue by jedie** [jedie/PyHardLinkBackup#39]
```
PyHardLinkBackup v0.12.1 - Django v2.2.11 manage command

read user configuration from:
	/home/jens/PyHardLinkBackup.ini

Use Database file: '/home/jens/PyHardLinkBackups.sqlite3'
temp log file: /tmp/pyhardlinkbackup_r0jfxi09.log
Performing system checks...

System check identified no issues (0 silenced).
Execute: 'PRAGMA journal_mode = MEMORY;'
Execute: 'PRAGMA temp_store = MEMORY;'
Execute: 'PRAGMA synchronous = OFF;'
March 05, 2020 - 21:48:43
Django version 2.2.11, using settings 'pyhardlinkbackup.django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 42, in get_internal_wsgi_application
    return get_wsgi_application()
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 135, in __init__
    self.load_middleware()
  File "/home/jens/PyHardLinkBackup/lib/python3.6/site-packages/django/core/handlers/base.py", line 37, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

```

**Comment by jedie** [comment]
fixed by https://github.com/jedie/PyHardLinkBackup/commit/dfb9037b9f60aa6ef9e8fc927866d58a5baa430d
